### ISSUE TITLE
Windows compilation failure (ERROR 2)

### ISSUE THREAD

**Issue by tapafon** [rmottola/Arctic-Fox#116]
Compilation stops in ever beginning with Error 2, even in dev tree. I used VS Community 2013 Update 5 and that instruction: [https://forum.palemoon.org/viewtopic.php?f=19&t=13556](url)
Including logs:
```
 0:01.46 c:\mozilla-build\mozmake\mozmake.EXE -f client.mk -s
 0:22.51 Adding client.mk options from c:/Arctic-Fox-dev/.mozconfig:
 0:22.51     MOZ_CO_PROJECT=browser
 0:22.51     MOZ_OBJDIR=c:/Arctic-Fox-dev/obj-i686-pc-mingw32
 0:22.51     OBJDIR=c:/Arctic-Fox-dev/obj-i686-pc-mingw32
 0:22.51     FOUND_MOZCONFIG=c:/Arctic-Fox-dev/.mozconfig
 0:22.51 cd c:/Arctic-Fox-dev/obj-i686-pc-mingw32
 0:22.51 c:/Arctic-Fox-dev/configure
 0:22.51 Adding configure options from c:/Arctic-Fox-dev/.mozconfig
 0:22.51   --enable-application=browser
 0:22.51   --enable-optimize=-O2
 0:22.51   --enable-jemalloc
 0:22.51   --enable-shared-js
 0:22.51   --enable-devtools
 0:22.51 loading cache ./config.cache
 0:22.51 checking host system type... i686-pc-mingw32
 0:22.51 checking target system type... i686-pc-mingw32
 0:22.51 checking build system type... i686-pc-mingw32
 0:22.51 checking for mawk... no
 0:22.51 checking for gawk... gawk
 0:22.51 checking for python2.7... /c/mozilla-build/python/python2.7
 0:22.51 Creating Python environment
 0:22.51 checking Python environment is Mozilla virtualenv... yes
 0:22.51 checking for perl5... no
 0:22.51 checking for perl... /usr/bin/perl
 0:22.51 checking for gcc... cl
 0:22.51 checking whether the C compiler (cl  ) works... no
 0:22.51 configure: error: installation or configuration problem: C compiler cannot create executables.
 0:22.51 ------ config.log ------
 0:22.51 configure:1290: checking for gawk
 0:22.51 configure:1374: checking for python2.7
 0:22.51 configure:1484: checking Python environment is Mozilla virtualenv
 0:22.51 configure:1702: checking for perl5
 0:22.51 configure:1702: checking for perl
 0:22.51 configure:3420: checking for gcc
 0:22.51 configure:3533: checking whether the C compiler (cl  ) works
 0:22.51 configure:3549: cl -o conftest    conftest.c  1>&5
 0:22.51 Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
 0:22.51 Copyright (C) Microsoft Corporation.  All rights reserved.
 0:22.51
 0:22.51 cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
 0:22.51 conftest.c
 0:22.51 conftest.c : fatal error C1001: An internal error has occurred in the compiler.
 0:22.51 (compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\p0io.c', line 2807)
 0:22.51  To work around this problem, try simplifying or changing the program near the locations listed above.
 0:22.51 Please choose the Technical Support command on the Visual C++
 0:22.51  Help menu, or open the Technical Support help file for more information
 0:22.51 configure: failed program was:
 0:22.51
 0:22.51 #line 3544 "configure"
 0:22.51 #include "confdefs.h"
 0:22.51
 0:22.51 main(){return(0);}
 0:22.51 configure: error: installation or configuration problem: C compiler cannot create executables.
 0:22.51 *** Fix above errors and then restart with\
 0:22.51                "c:/mozilla-build/mozmake/mozmake.EXE -f client.mk build"
 0:22.51 c:/Arctic-Fox-dev/client.mk:360: recipe for target 'configure' failed
 0:22.51 mozmake.EXE[2]: *** [configure] Error 1
 0:22.51 c:/Arctic-Fox-dev/client.mk:374: recipe for target 'c:/Arctic-Fox-dev/obj-i686-pc-mingw32/Makefile' failed
 0:22.51 mozmake.EXE[1]: *** [c:/Arctic-Fox-dev/obj-i686-pc-mingw32/Makefile] Error 2
 0:22.51 client.mk:171: recipe for target 'build' failed
 0:22.51 mozmake.EXE: *** [build] Error 2
 0:22.53 0 compiler warnings present.
2
```

**Comment by rmottola** [comment]
I do not work on windows. @roytam1 does, with VisualStudio. I am happy if somebody can build on windows, but I cannot personally test or fix it. It seems that the build system doesn't like your compiler.

**Comment by roytam1** [comment]
VS2017 is too new to build ArcticFox. you need to use VS2013 update 5 to build (from my `winbuild` branch in my fork)

**Comment by roytam1** [comment]
> I'm already using VS2013 update 5

```
0:22.51 Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
```
cl version 18 is VS2017.

**Comment by tapafon** [comment]
Sorry, I accidentally closed an issue too early.
Anyway, I reinstalled everything and error now is different. Do I need to install DirectX SDK as well?
```
0:01.35 c:\mozilla-build\mozmake\mozmake.EXE -f client.mk -s
 0:39.80 Adding client.mk options from c:/Arctic-Fox-winbuild/.mozconfig:
 0:39.80     MOZ_CO_PROJECT=browser
 0:39.80     MOZ_OBJDIR=c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32
 0:39.80     OBJDIR=c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32
 0:39.80     FOUND_MOZCONFIG=c:/Arctic-Fox-winbuild/.mozconfig
 0:39.80 cd c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32
 0:39.80 c:/Arctic-Fox-winbuild/configure
 0:39.81 Adding configure options from c:/Arctic-Fox-winbuild/.mozconfig
 0:39.81   --enable-application=browser
 0:39.81   --enable-optimize=-O2
 0:39.81   --enable-jemalloc
 0:39.81   --enable-shared-js
 0:39.81   --enable-devtools
 0:39.81 loading cache ./config.cache
 0:39.81 checking host system type... i686-pc-mingw32
 0:39.81 checking target system type... i686-pc-mingw32
 0:39.81 checking build system type... i686-pc-mingw32
 0:39.81 checking for mawk... no
 0:39.81 checking for gawk... gawk
 0:39.81 checking for python2.7... /c/mozilla-build/python/python2.7
 0:39.81 Creating Python environment
 0:39.81 checking Python environment is Mozilla virtualenv... yes
 0:39.81 checking for perl5... no
 0:39.81 checking for perl... /usr/bin/perl
 0:39.81 checking for gcc... cl
 0:39.81 checking whether the C compiler (cl  ) works... yes
 0:39.81 checking whether the C compiler (cl  ) is a cross-compiler... no
 0:39.81 checking whether we are using GNU C... no
 0:39.81 checking whether cl accepts -g... no
 0:39.81 checking for c++... cl
 0:39.81 checking whether the C++ compiler (cl  ) works... yes
 0:39.81 checking whether the C++ compiler (cl  ) is a cross-compiler... no
 0:39.81 checking whether we are using GNU C++... no
 0:39.81 checking whether cl accepts -g... no
 0:39.81 checking for ranlib... :
 0:39.81 checking for ml... /c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64_x86/ml
 0:39.81 checking for ar... no
 0:39.81 checking for ld... link
 0:39.81 checking for strip... no
 0:39.81 checking for windres... no
 0:39.81 checking for otool... no
 0:39.81 checking for rustc... no
 0:39.81 checking for midl... midl
 0:39.81 checking for overridable _RAISE... yes
 0:39.81 checking for highest Windows version supported by this SDK... 0x0603
 0:39.81 checking for Windows SDK being recent enough... yes
 0:39.81 checking how to run the C preprocessor... cl -E -nologo
 0:39.81 checking how to run the C++ preprocessor... cl -TP -E -nologo
 0:39.81 checking for a BSD compatible install... /usr/bin/install -c
 0:39.81 checking whether ln -s works... no
 0:39.81 checking for minimum required perl version >= 5.006... 5.008008
 0:39.81 checking for full perl installation... yes
 0:39.81 checking for doxygen... :
 0:39.81 checking for autoconf... /usr/bin/autoconf
 0:39.81 checking for unzip... /c/mozilla-build/info-zip/unzip
 0:39.81 checking for zip... /c/mozilla-build/info-zip/zip
 0:39.81 checking for xargs... /usr/bin/xargs
 0:39.81 checking for rpmbuild... :
 0:39.81 checking for c:/mozilla-build/mozmake/mozmake.EXE... c:/Arctic-Fox-winbuild/configure: line 5750: test: /usr/local/bin/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/7zip/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/info-zip/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/kdiff3/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/mozmake/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/nsis-3.0b1/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/nsis-2.46u/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/python/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/python/Scripts/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/upx391w/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/wget/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/yasm/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: ./c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /usr/local/bin/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /usr/mingw/bin/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /usr/bin/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/MSBuild/12.0/bin/amd64/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64_x86/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Windows/Microsoft.NET/Framework64/v4.0.30319/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/VCPackages/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/Tools/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/HTML Help Workshop/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/Team Tools/Performance Tools/x64/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft Visual Studio 12.0/Team Tools/Performance Tools/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Windows Kits/8.1/bin/x64/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Windows Kits/8.1/bin/x86/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Program Files (x86)/Microsoft SDKs/Windows/v8.1A/bin/NETFX 4.5.1 Tools/x64//c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Windows/System32/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Windows/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/Windows/System32/Wbem/c: binary operator expected
 0:39.81 c:/Arctic-Fox-winbuild/configure: line 5750: test: /c/mozilla-build/moztools-x64/bin/c: binary operator expected
 0:39.81 no
 0:39.83 checking for make... /usr/local/bin/make
 0:39.83 checking for X... no
 0:39.83 checking that static assertion macros used in autoconf tests work... yes
 0:39.83 c:/Arctic-Fox-winbuild/configure: line 8687: test: : integer expression expected
 0:39.83 checking for 64-bit OS... no
 0:39.83 checking whether the C++ compiler (cl  -TP -nologo -D_HAS_EXCEPTIONS=0 -W3 -Gy -arch:IA32 -FS -wd4251 -wd4244 -wd4267 -wd4345 -wd4351 -wd4482 -wd4800 -wd4819 -we4553 -GR-  -LARGEADDRESSAWARE -NXCOMPAT -OPT:REF -OPT:ICF=15 -DYNAMICBASE -SAFESEH) actually is a C++ compiler... yes
 0:39.83 checking for malloc.h... yes
 0:39.83 checking for alloca.h... no
 0:39.83 checking for strndup... no
 0:39.83 checking for posix_memalign... no
 0:39.83 checking for memalign... no
 0:39.83 checking for malloc_usable_size... no
 0:39.83 checking for malloc.h... (cached) yes
 0:39.83 checking whether malloc_usable_size definition can use const argument... yes
 0:39.83 checking for valloc in malloc.h... no
 0:39.83 checking for valloc in unistd.h... no
 0:39.83 checking NSPR selection... source-tree
 0:39.83 checking for YASM assembler... checking for yasm... yasm
 0:39.83 checking for application to build... browser
 0:39.83 checking if app-specific confvars.sh exists... c:/Arctic-Fox-winbuild/browser/confvars.sh
 0:39.83 checking __attribute__ ((aligned ())) support... trying 64
 0:39.83 trying 32
 0:39.83 trying 16
 0:39.83 trying 8
 0:39.83 0
 0:39.83 checking for java... :
 0:39.83 checking for javac... :
 0:39.83 checking for javah... :
 0:39.83 checking for jar... :
 0:39.83 checking for jarsigner... :
 0:39.83 checking for keytool... :
 0:39.83 Found D3D compiler in Windows SDK 8.1.
 0:39.83 Found MOZ_D3DCOMPILER_VISTA_DLL_PATH: C:\Program Files (x86)\Windows Kits\8.1\/Redist/D3D/x86/d3dcompiler_47.dll
 0:39.83 ERROR: Invalid key name.
 0:39.83 Type "REG QUERY /?" for usage.
 0:39.83 DirectX SDK not found.
 0:39.83 Couldn't find an acceptable DirectX SDK for ANGLE, needed for d3dcompiler_43.
 0:39.89 Found d3dcompiler DLL for Vista+: d3dcompiler_47.dll
 0:39.89 configure: error: Both D3D compilers _43 and _46+ are required by --enable-require-d3d-compilers.
 0:39.89 ------ config.log ------
 0:39.89 configure:20279: cl -c  -TC -nologo -D_HAS_EXCEPTIONS=0 -W3 -Gy -arch:IA32 -FS -wd4244 -wd4267 -wd4819 -we4553 -Werror  conftest.c 1>&5
 0:39.89 cl : Command line error D8021 : invalid numeric argument '/Werror'
 0:39.89 configure: failed program was:
 0:39.89 #line 20272 "configure"
 0:39.89 #include "confdefs.h"
 0:39.89
 0:39.89 int main() {
 0:39.89 static char c __attribute__ ((aligned(16))) = 0; return c;
 0:39.89 ; return 0; }
 0:39.89 configure:20279: cl -c  -TC -nologo -D_HAS_EXCEPTIONS=0 -W3 -Gy -arch:IA32 -FS -wd4244 -wd4267 -wd4819 -we4553 -Werror  conftest.c 1>&5
 0:39.89 cl : Command line error D8021 : invalid numeric argument '/Werror'
 0:39.89 configure: failed program was:
 0:39.89 #line 20272 "configure"
 0:39.89 #include "confdefs.h"
 0:39.89
 0:39.89 int main() {
 0:39.89 static char c __attribute__ ((aligned(8))) = 0; return c;
 0:39.89 ; return 0; }
 0:39.89 configure:21441: checking for java
 0:39.89 configure:21490: checking for javac
 0:39.89 configure:21539: checking for javah
 0:39.89 configure:21588: checking for jar
 0:39.89 configure:21637: checking for jarsigner
 0:39.89 configure:21686: checking for keytool
 0:39.89 configure: error: Both D3D compilers _43 and _46+ are required by --enable-require-d3d-compilers.
 0:39.89 *** Fix above errors and then restart with\
 0:39.89                "c:/mozilla-build/mozmake/mozmake.EXE -f client.mk build"
 0:39.89 c:/Arctic-Fox-winbuild/client.mk:360: recipe for target 'configure' failed
 0:39.89 mozmake.EXE[2]: *** [configure] Error 1
 0:39.89 c:/Arctic-Fox-winbuild/client.mk:374: recipe for target 'c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32/Makefile' failed
 0:39.89 mozmake.EXE[1]: *** [c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32/Makefile] Error 2
 0:39.89 client.mk:171: recipe for target 'build' failed
 0:39.89 mozmake.EXE: *** [build] Error 2
 0:39.92 0 compiler warnings present.
2
```

**Comment by roytam1** [comment]
> Do I need to install DirectX SDK as well?

yes

**Comment by tapafon** [comment]
Now it complains about moz.build file (NOT .mozbuild)
```
 4:32.46 Walking the dog...
 4:32.46 Traceback (most recent call last):
 4:32.46   File "./config.status", line 1241, in <module>
 4:32.46     config_status(**args)
 4:32.46   File "c:\Arctic-Fox-winbuild\python\mozbuild\mozbuild\config_status.py", line 135, in config_status
 4:32.46     summary = the_backend.consume(definitions)
 4:32.46   File "c:\Arctic-Fox-winbuild\python\mozbuild\mozbuild\backend\base.py", line 180, in consume
 4:32.46     for obj in objs:
 4:32.46   File "c:\Arctic-Fox-winbuild\python\mozbuild\mozbuild\frontend\emitter.py", line 175, in emit
 4:32.46     objs = list(self._emit_libs_derived(contexts))
 4:32.46   File "c:\Arctic-Fox-winbuild\python\mozbuild\mozbuild\frontend\emitter.py", line 211, in _emit_libs_derived
 4:32.46     self._link_libraries(context, obj, variable)
 4:32.46   File "c:\Arctic-Fox-winbuild\python\mozbuild\mozbuild\frontend\emitter.py", line 324, in _link_libraries
 4:32.46     context)
 4:32.46 mozbuild.frontend.reader.SandboxValidationError:
 4:32.46 ==============================
 4:32.46 ERROR PROCESSING MOZBUILD FILE
 4:32.46 ==============================
 4:32.46
 4:32.46 The error occurred while processing the following file or one of the files it includes:
 4:32.48
 4:32.48     c:/Arctic-Fox-winbuild/toolkit/mozapps/update/updater/moz.build
 4:32.48
 4:32.48 The error occurred when validating the result of the execution. The reported error is:
 4:32.48
 4:32.48     USE_LIBS contains "updatecommon-standalone", which does not match any LIBRARY_NAME in the tree.
 4:32.48
 4:32.48
 4:32.48 *** Fix above errors and then restart with\
 4:32.48                "c:/mozilla-build/mozmake/mozmake.EXE -f client.mk build"
 4:32.48 c:/Arctic-Fox-winbuild/client.mk:360: recipe for target 'configure' failed
 4:32.48 mozmake.EXE[2]: *** [configure] Error 1
 4:32.48 c:/Arctic-Fox-winbuild/client.mk:374: recipe for target 'c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32/Makefile' failed
 4:32.48 mozmake.EXE[1]: *** [c:/Arctic-Fox-winbuild/obj-i686-pc-mingw32/Makefile] Error 2
 4:32.48 client.mk:171: recipe for target 'build' failed
 4:32.48 mozmake.EXE: *** [build] Error 2
 4:32.49 0 compiler warnings present.
2
```

**Comment by roytam1** [comment]
I don't build updater, so you may need to fix updater script by yourself or specify `ac_add_options --disable-updater` in your `.mozconfig`

**Comment by tapafon** [comment]
It finally built! It works not so good under Windows 11, but it isn't a problem since it designed for XP.

**Comment by rmottola** [comment]
Exacty, we don't have an updater inrastructure, so it needs to be disabled, that part is not made to be built.
Well, I don't know the status on Windows, maybe it is some CSS/aspect issue at runtime? if it is stuff like buttons, looks, tabs.
If it is crashes, then it might be a different build configuration.
